Initialize the repository
skillslab/.github pull request #1
Opened 2023-04-19 08:52 UTC by SpritzerPyro

# Description

Initialize the repository with a pull request template and a check labels workflow

# Meta Information

Link to Issue: https://jira.anton-paar.com/browse/SLAB-6627

# TODOs

- [x] Add the appropriate label(s)
- [x] Add reviewer(s)

2023-04-19 09:21 UTC, math-and-data requested changes

2023-04-19 09:21 UTC, math-and-data commented on workflows/check-labels.yml
> +          any_of: breaking,bugfix,client request,dependencies,documentation,feature,visualization
```suggestion
          any_of: breaking,bugfix,client request,dependencies,documentation,feature,tests,visualization
```

2023-04-19 09:23 UTC, math-and-data approved these changes

2023-04-25 08:51 UTC, Christof approved these changes

2023-04-25 08:52 UTC, merged