Add all repositories to the label syncer
skillslab/.github pull request #7
Opened 2023-02-17 12:44 UTC by SpritzerPyro

# Description

Add all repositories of the skillslab organization to the sync-labels GitHub workflow repositories.

# Meta Information

Link to Issue: https://jira.anton-paar.com/browse/SLAB-6398

# TODOs

- [x] Add the appropriate label(s)
- [x] Add reviewer(s)
- [ ] @Christof Please check whether we should exclude some repositories
- [ ] @Christof @Naehil I took the colors from the [confluence page](https://confluence.anton-paar.com/pages/viewpage.action?spaceKey=SKILLSLAB&title=2023-01-31+Retrospective). Are they ok or should we change something ([check here](https://github.com/skillslab/.github/labels))? For example, I think feature is a bit weak...

2023-02-20 12:06 UTC, hannamagdalena approved these changes

2023-02-20 12:34 UTC, Christof requested changes

2023-02-20 12:34 UTC, Christof commented on .github/workflows/sync-labels.yml
> +            skillslab/ANT-Library
For now just specify projects with a build process defined by us

2023-02-21 12:53 UTC, Christof approved these changes

2023-02-21 12:53 UTC, merged